version: "3.9"

services:
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - frontend
      - backend

  frontend:
    image: (shubhpatel1609)/frontend:latest
    depends_on:
      - backend

  backend:
    image: (shubhpatel1609)/backend:latest
    environment:
      MONGO_URL: mongodb://mongodb:27017/studentdb
    depends_on:
      - mongodb

  mongodb:
    image: mongo:7
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
